#Spring Boot App
version: '3.1'
services:
  app:
    container_name: diploma-app-backend
    image: diploma-app-backend
    build:
      context: miras-aigera-diploma-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgresqldb
    environment:
      DB_HOST: postgresqldb
      DB_PORT: 5432
      DB_NAME: lost-found-app
      DB_USER: postgres
      DB_PASSWORD: zxc
      DDL_AUTO: update
    networks:
      - backend

  #PostgreSQL DB
  postgresqldb:
    image: postgres
    container_name: diploma-postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=zxc
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lost-found-app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - backend

networks:
  backend:
    driver: bridge