#Spring Boot App
version: '3.1'
services:
  app:
    container_name: citizen-guard-server
    image: 51827/citizen-guard-server:3.0
    build:
      context: miras-aigera-diploma-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgresqldb
    environment:
      DB_HOST: postgresqldb
      DB_PORT: 5432
      DB_NAME: citizen-guard-db
      DB_USER: postgres
      DB_PASSWORD: zxc
      MINIO_REGION: ru-central1-a
      MINIO_ACCESS_KEY: citizen-guard
      MINIO_SECRET_KEY: Wbul0ZKySm7EUjRL10mVs0EFNnsk35B1
      MINIO_BUCKET: citizen-guard-photos
      MINIO_HOST: http://194.110.55.6:9000
    networks:
      - backend

  #PostgreSQL DB
  postgresqldb:
    image: postgres
    container_name: diploma-postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: zxc
      POSTGRES_USER: postgres
      POSTGRES_DB: citizen-guard-db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      TZ: Asia/Almaty
    networks:
      - backend

networks:
  backend:
    driver: bridge