#BackEnd Spring Boot App
version: '3.1'
services:
  app:
    container_name: diploma-app-backend
    image: diploma-app-backend
    build:
      context: miras-aigera-diploma-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgresqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/lost-found-app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: zxc
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend

#Postgresql DataBase
  postgresqldb:
    image: postgres
    container_name: diploma-postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=zxc
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lost-found-app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - backend

networks:
  backend:
    driver: bridge