insert into cities(name)
values ('Aktau'),
       ('Aktobe'),
       ('Atyrau'),
       ('Zhezkazgan'),
       ('Karaganda'),
       ('Kokshetau'),
       ('Konaev'),
       ('Kostanay'),
       ('Kyzylorda'),
       ('Pavlodar'),
       ('Petropavlovsk'),
       ('Semey'),
       ('Taldykorgan'),
       ('Taraz'),
       ('Turkestan'),
       ('Uralsk'),
       ('Ust-Kamenogorsk'),
       ('Astana'),
       ('Almaty');