#DB
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lost-found-app}?serverTimezone=Asia/Almaty
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:zxc}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#JWT token
security:
  jwt:
    token:
      secret-key: mirasmadiyevandaigerimbexeit
      expiration: 3600000

#Swagger
springdoc:
  swagger-ui:
    configUrl: /api/v1/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /api/v1/api-docs
  api-docs:
    path: /api/v1/api-docs
    version: openapi_3_0

#Actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health, prometheus, info, env, beans'
    jmx:
      exposure:
        include: 'health, prometheus, info, env, beans'
  endpoint:
    metrics:
      enabled: true

#Minio
cloud:
  minio:
    region.static: ${MINIO_REGION:ru-central1-a}
    credentials:
      accessKey: ${MINIO_ACCESS_KEY:citizen-guard}
      secretKey: ${MINIO_SECRET_KEY:Wbul0ZKySm7EUjRL10mVs0EFNnsk35B1}
    bucket: ${MINIO_BUCKET:citizen-guard-photos}
    host: ${MINIO_HOST:http://localhost:9000}
#Server
server:
  port: 8080
  compression:
    enabled: true

#Application info
application:
  title: CitizenGuard service
  version: v1.0


