#DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lost-found-app
    username: postgres
    password: zxc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update



#JWT token
security:
  jwt:
    token:
      secret-key: mirasmadiyevandaigerimbexeit
      expiration: 3600000

#Swagger
springdoc:
  swagger-ui:
    configUrl: /api/v1/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /api/v1/api-docs
  api-docs:
    path: /api/v1/api-docs

#Server
server:
  port: 8080

#Application
application:
  title: Lost found service application
  version: v1.0


