#DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lost-found-app
    username: postgres
    password: zxc
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public

#JWT token
security:
  jwt:
    token:
      secret-key: mirasmadiyevandaigerimbexeit
      expiration: 3600000

#Swagger
springdoc:
  swagger-ui:
    configUrl: /api/v1/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /api/v1/api-docs
  api-docs:
    path: /api/v1/api-docs
    version: openapi_3_0

#Actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health, prometheus, info, env, beans'
    jmx:
      exposure:
        include: 'health, prometheus, info, env, beans'
  endpoint:
    metrics:
      enabled: true
#Server
server:
  port: 8080
  compression:
    enabled: true

#Application
application:
  title: Lost found service application
  version: v1.0


